// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ML_NETML.Model
{
    public class ModelInput
    {
        [ColumnName("x"), LoadColumn(0)]
        public float X { get; set; }


        [ColumnName("item_id"), LoadColumn(1)]
        public float Item_id { get; set; }


        [ColumnName("name"), LoadColumn(2)]
        public string Name { get; set; }


        [ColumnName("category"), LoadColumn(3)]
        public string Category { get; set; }


        [ColumnName("price"), LoadColumn(4)]
        public float Price { get; set; }


        [ColumnName("old_price"), LoadColumn(5)]
        public string Old_price { get; set; }


        [ColumnName("sellable_online"), LoadColumn(6)]
        public bool Sellable_online { get; set; }


        [ColumnName("link"), LoadColumn(7)]
        public string Link { get; set; }


        [ColumnName("other_colors"), LoadColumn(8)]
        public bool Other_colors { get; set; }


        [ColumnName("short_description"), LoadColumn(9)]
        public string Short_description { get; set; }


        [ColumnName("designer"), LoadColumn(10)]
        public string Designer { get; set; }


        [ColumnName("depth"), LoadColumn(11)]
        public float Depth { get; set; }


        [ColumnName("height"), LoadColumn(12)]
        public float Height { get; set; }


        [ColumnName("width"), LoadColumn(13)]
        public float Width { get; set; }


    }
}
