// This file was auto-generated by ML.NET Model Builder. 

using System;
using ML_NETML.Model;

namespace ML_NETML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Category = @"Bar furniture",
                Old_price = @"No old price",
                Sellable_online = true,
                Designer = @"Nicholai Wiig Hansen",
                Depth = 0F,
                Height = 99F,
                Width = 51F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");
            Console.WriteLine($"Category: {sampleData.Category}");
            Console.WriteLine($"Old_price: {sampleData.Old_price}");
            Console.WriteLine($"Sellable_online: {sampleData.Sellable_online}");
            Console.WriteLine($"Designer: {sampleData.Designer}");
            Console.WriteLine($"Depth: {sampleData.Depth}");
            Console.WriteLine($"Height: {sampleData.Height}");
            Console.WriteLine($"Width: {sampleData.Width}");
            Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
